name: BlocksTowerDefence1.0
version: '${project.version}'
main: ksucapproj.blockstowerdefence1.BlocksTowerDefence1
api-version: '1.21'
authors:
  - mthyuu
  - Wayneistaken
  - NekoPara
  - ashjuno
  - AnnaGrace_2

commands:
  summontower:
    description: Summon a tower at your location
    usage: /summontower
    permission: summontower.use
  startgame:
    description: Start the tower defense game
    usage: /startgame
  upgradetower:
    description: Upgrade a tower
    usage: /upgradetower
  spawnzombie:
    description: Spawns a zombie with a health bar.
    usage: /spawnzombie
    permission: spawnzombie.use
    permission-message: You do not have permission to use this command.
  mtd:
    description: MTD command with corresponding subcommands
    usage: /mtd <subcommand>
  readyup:
    description: start the next round
    usage: /readyup