# THIS IS THE BTD CONFIG FILE

# If the value is blank or is the commented out value next to its input, it is default
# If the value is blank and has no comment, it has no default value
# -- Example --
# default-time: 450 # 1000
# This means the current default time is 450, but the default value is 1000




btd:
  settings:
    daylight-cycle:
      enable: false # false
      default-time: 1000 # 1000

    weather-cycle:
      enable: false # false
      default-weather:

    natural-mob-spawn:
    motd:
      enable: false # false
      message:
    greet-player:
      enable: true # true
      message:



  spawn:
    world:
    x:
    y:
    z:
    yaw:
    pitch:

  attributes:

    upgrades:

      #
      #    //////////////////////// For Upgrades Related to Potion Effects /////////////////////////////
      #    * If the maximum desired tier of an effect is n, use n as the default
      #        - ex: if speed 5 is the desired maximum, choose 5 as the max default
      #

      # these multipliers are not set up yet
      universal:
        max-level:
        cost-multiplier: 1 # 1 # this is not set up yet

      players:
        speed:
          max-level: 5 # 5
          cost: 500 # 500

        strength:
          max-level: 5 # 5
          cost: 750 # 750

        sword:
          material:
            max-level: 5 # 5
            cost: 400 # 400

          slowness:
            max-level: 5 # 5
            cost: 400 # 400
            duration:
              ticks: 10 # 10
              increase-duration-on-upgrade: false # false

          sweeping-edge:
            max-level: 5 # 5
            cost: 400 # 400


      towers:

        # these multipliers are not set up yet
        universal:
          upgrade-strength-multiplier: 1 # 1 # this is not set up yet
          cost-multiplier: 1 # 1 # this is not set up yet

        basic:
          cost: 500 # 500
          tier-one:

        fast:
          cost: 300 # 300
          tier-one:

        sniper:
          cost: 750 # 750
          tier-one:

        splash:
          cost: 900 # 900
          tier-one:

        slow:
          cost: 450 # 450
          tier-one:


    mobs:

      # these multipliers are not set up yet
      universal:
        health-multiplier:
        reward-multiplier:

      zombie:
        reward:

      iron-golem:
        reward:

      witch:
        reward:

      enderman:
        reward:

      piglin:
        reward:

      blaze:
        reward:


    players:
      round-end-bonus:
        # the round-end bonus is calculated: (base-reward + (reward-per-round * round num))
        # this means per round, the default round-end-bonus is: (100 + (1 * round num))
        base-reward: 100 # 100
        reward-per-round: 1 # 1
      attribute-multipliers:
        # all values have a default of 1.0x multiplier
        # this means if the multiplier for speed is 2, the player moves 2x speed than normal by default
        attack:
          speed:
          range:
          damage:

        base-speed:







