server:
  settings:
    daylight-cycle:
      default-time:

    weather-cycle:
      default-weather:

    natural-mob-spawn:
    motd:
      enable:
      message:
    greet-player:
      enable:
      message:



  spawn:
    world: # world
    x: # 78
    y: # 108
    z: # -709
    yaw: # 179.81284
    pitch: # 5.829553

  database:
    url: # jdbc:sqlite:F:\IntelliJ Projects\BlocksTD1.0\src\main\resources\test_db.db

  attributes:

    upgrades:

      #
      #    //////////////////////// For Upgrades Related to Potion Effects /////////////////////////////
      #    * If the maximum desired tier of an effect is n, use n as the default
      #        - ex: if speed 5 is the desired maximum, choose 5 as the max default
      #

      # these multipliers are not set up yet
      universal:
        max-level:
        cost-multiplier:

      players:
        speed:
          max-level:
          cost:

        strength:
          max-level:
          cost:

        sword:
          material:
            max-level:
            cost:

          slowness:
            max-level:
            cost:
            duration:
              increase-duration-on-upgrade:

          sweeping-edge:
            max-level:
            cost:


      towers:

        # these multipliers are not set up yet
        universal:
          upgrade-strength-multiplier:
          cost-multiplier:

        basic:
          cost:
          tier-one:

        fast:
          cost:
          tier-one:

        sniper:
          cost:
          tier-one:

        splash:
          cost:
          tier-one:

        slow:
          cost:
          tier-one:


    mobs:

      # these multipliers are not set up yet
      universal:
        health-multiplier:
        reward-multiplier:

      zombie:
        reward:

      iron-golem:
        reward:

      witch:
        reward:

      enderman:
        reward:

      piglin:
        reward:

      blaze:
        reward:


    players:
      round-end-bonus:
      attribute-multipliers:
        attack:
          speed:
          range:
          damage:

        base-speed:







