server:
  settings:
    daylight-cycle:
      default-time:

    weather-cycle:
      default-weather:

    natural-mob-spawn:


  spawn:
    world:
    x:
    y:
    z:
    yaw:
    pitch:

  database:
    url:

  upgrades:

    #
    #    //////////////////////// For Upgrades Related to Potion Effects /////////////////////////////
    #    * If the maximum desired tier of an effect is n, use n as the default
    #        - ex: if speed 5 is the desired maximum, choose 5 as the max default
    #

    universal:
      max-level:
      cost-multiplier:

    player:
      speed:
        max-level:
        cost:

      strength:
        max-level:
        cost:

      sword:
        material:
          max-level:
          cost:

        slowness:
          max-level:
          cost:
          duration:
            increase-duration-on-upgrade:

        sweeping-edge:
          max-level:
          cost:


  economy:
    mobs:
      health-multiplier:
      reward-multiplier:

      zombie:
        reward:

      skeleton:
        reward:

    players:
      attribute-multipliers:
        attack:
          speed:
          range:
          damage:

        base-speed:
