name: pluginTest
version: '1.0-SNAPSHOT'
main: me.matthewTest.pluginTest.PluginTest
api-version: '1.21'
authors:
  - mthyuu
  - Wayneistaken
  - NekoPara
  - ashjuno
  - AnnaGrace_2

commands:
  mtd:
    description: MTD command with corresponding subcommands
    usage: /mtd <subcommand>
  test:
    description: Test command
    usage: /test
  hello:
    description: Command that says hello
    usage: /hello

depend:
  - PlaceholderAPI
